---
title: "R Visualization"
output:
  word_document: default
  pdf_document: default
date: "2023-10-01"
---

```{r}
setwd ("/Users/jumaabdi/Desktop/G_P/Spring23/RDS/Homework/HW6")
library(markdown)
library(ggplot2) 
library(tidyverse)
library(maps)
library(usmap)
library(htmltab)
library(ggmap)
library(jsonlite)
```

## R Markdown

```{r reading data}

nlsy_data <- read.table(file = "/Users/jumaabdi/Desktop/G_P/Spring23/RDS/Homework/HW6/nlsy.txt", header = TRUE, na.string = ".")
verbal <- nlsy_data$V3
math <- nlsy_data$V4
sex <-nlsy_data$sex
```



```{r histogram generation for math and verbal}
ggplot(data = nlsy_data, aes(x = math)) +
  geom_histogram(bins = 30, aes(y = after_stat(density))) + 
  geom_density(linewidth=1.5, color='red')

ggplot(data = nlsy_data, aes(x = verbal)) +
  geom_histogram(bins = 30, aes(y = after_stat(density))) + 
  geom_density(linewidth=1.5, color='red')
```
```{r generating scatter plot}

ggplot(data = nlsy_data) + 
  geom_jitter(aes(math, verbal, color = math))

#adding a regression line

ggplot(data = nlsy_data, aes(math, verbal, color = math)) +
  geom_jitter()+
  geom_smooth(method = lm, formula = y ~ x, se=F)+
  labs(title = "Correlation between math and verbal scores",
       x = "Math Score", y = "Verbal Score")

```


```{r comparing male and female participants}

nlsy_data$sex2 <- factor(nlsy_data$sex, 
                      levels=1:2, 
                      labels=c('Male', 'Female'))
ggplot(data = nlsy_data, aes(math, verbal, color = sex2)) + 
  geom_jitter()+
  geom_smooth(method=lm, formula=y~x, se=FALSE) + 
  scale_color_discrete(name="By Sex")
```
```{r mapping population data}

# Parsing data from the webpage
population <- htmltab(doc="https://www.ipl.org/div/stateknow/popchart.html", which = 2)

# Renaming columns
colnames(population)[3] <- "population"
colnames(population)[2] <- "region"

# Converting string data to integer
population$population <- as.integer(gsub(",", "", population$population))

# Convert region names to lowercase for consistency
population$region <- tolower(population$region)

# Get state data in the form of latitude and longitude coordinates
usa_map <- map_data('state')

# Merging the population and state data
us_map_pop <- merge(usa_map, population, by.x = "region", by.y = "region", all.x = TRUE)

# Creating map by plotting the data
map_graph <- ggplot(data = us_map_pop) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = population), 
               color = "black") +
  scale_fill_gradient(low = "white", high = "purple", na.value = "gray", trans = 'log10') +
  labs(title = "Population by State", fill = "Population") +
  coord_fixed(1.3)
print(map_graph)

```

